// src/components/Footer.svelte
<footer>
	<hr />
	<small> Everything on this website is MIT lisensed. It was written by Dave Mackintosh. </small>
	<div>
		<small>
			<a
				href="https://github.com/davemackintosh"
				rel="noopen no-referrer"
				title="Dave Mackintosh&#x27;s Github profile"
			>
				<div>
					<svg
						stroke="currentColor"
						fill="currentColor"
						stroke-width="0"
						viewBox="0 0 16 16"
						height="1em"
						width="1em"
						xmlns="http://www.w3.org/2000/svg"
					>
						<path
							fill-rule="evenodd"
							d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"
						/>
					</svg>
				</div>
				Github</a
			>
		</small>
	</div>
</footer>

// src/shared/components/footer/footer.tsx
import React from "react"
import styled from "styled-components"
import { GoMarkGithub } from "react-icons/go"
import { IoLogoTwitter } from "react-icons/io"
import theme from "@src/shared/theme/theme"
import { Grid } from "@src/shared/theme/grid"

const Small = styled.small`
  color: ${theme.colors.fontUnimportant};
  display: block;
`

const StyledFooter = styled.footer`
  width: 80vw;
  margin: 2em auto;
`

const LinkGrid = styled(Grid("div"))``
const Icon = styled.div`
  display: inline-block;
  margin-right: 1em;
  vertical-align: sub;
`

function Footer(): JSX.Element {
  return (
    <StyledFooter>
      <Small>Everything on this website is MIT lisensed.</Small>
      <Small>It was written by Dave Mackintosh.</Small>
      <hr />
      <LinkGrid>
        <Small>
          <a
            href="https://twitter.com/daveymackintosh"
            rel="noopen no-referrer"
            title="Dave Mackintosh's Twitter profile"
          >
            <Icon>
              <IoLogoTwitter />
            </Icon>
            Twitter
          </a>
        </Small>
        <Small>
          <a
            href="https://github.com/davemackintosh"
            rel="noopen no-referrer"
            title="Dave Mackintosh's Github profile"
          >
            <Icon>
              <GoMarkGithub />
            </Icon>
            Github
          </a>
        </Small>
      </LinkGrid>
    </StyledFooter>
  )
}

export default Footer
